### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by cjihrig** [nodejs/uvwasi#11]
There are a number of TODO comments sprinkled throughout the code. A number of them are Windows specific. The most important are probably in `uvwasi__is_absolute_path()` and `uvwasi__resolve_path()`. Once those ones are resolved there will still be some Windows limitations, but libuv should smooth out most of them.

**Comment by gengjiawen** [comment]
https://github.com/cjihrig/uvwasi/blob/e5e168e4516e960c363c93bd438f254968f19ed0/src/fd_table.c#L117

This is not support on windows. See https://github.com/cjihrig/uvwasi/pull/27#issuecomment-541381257.

**Comment by tniessen** [comment]
@gengjiawen Possible fix in #30. Obviously won't work for sockets etc.

**Comment by gengjiawen** [comment]
> @gengjiawen Possible fix in #30. Obviously won't work for sockets etc.

Yeap. Other macros works in mingw except `S_ISSOCK`.

**Comment by cjihrig** [comment]
Current state of known Windows issues:

- `fd_fdstat_get()` sets the resulting `uvwasi_fdstat_t`'s `fs_flags` field to 0. This can be improved.
- `fd_fdstat_set_flags()` is not supported on Windows. I'm not sure if this can be improved.
- `fd_readdir()` does not currently work on Windows. The API itself is awkward here, but support can be improved here (but might require not using libuv).
- `poll_oneoff()` is not implemented on Windows or any other platform yet.

**Comment by Paril** [comment]
Executables don't have stdin/out/err which causes `uvwasi__insert_stdio` to fail. Ideally there should be a flag to exclude these/void them out.
