### ISSUE TITLE
How to avoid pulling in libuv?

### ISSUE THREAD

**Issue by saghul** [nodejs/uvwasi#165]
👋 

I'm trying to use uvwasi in [txiki.js](https://github.com/saghul/txiki.js) through wasm3. I'm already using libuv, in my project and thus embedding it again with uvwasi is being problematic.

What would be the way to accomplish this? Perhaps have a CMake option to skip pulling libuv, so the one already provided is used?

Thanks!

**Comment by cjihrig** [comment]
I think that sounds like a good idea. Node [recently did something similar in their gyp file](https://github.com/nodejs/node/commit/f65d748f5805bb778b0bcbb808bfcde053149f60).

**Comment by cjihrig** [comment]
@saghul compared to what is [currently done](https://github.com/nodejs/uvwasi/blob/44542cccbdccb2d322d0a2759c2ec6d158bc2c56/CMakeLists.txt#L30-L33), would something like this work for you?

```
FetchContent_Declare(
        libuv
        URL /path/to/your/libuv)
```

**Comment by saghul** [comment]
I think #164 would work best.
