### ISSUE TITLE
uvwasi team working tasks

### ISSUE THREAD

**Issue by mhdawson** [nodejs/uvwasi#187]
As discussed in the recent meeting with @cjihrig, @phated, @ospencer, @guybedford and myself

1) Refactor build so that uvwasi can be used as shared library
    - Oscar and Blain will work on PRs for this, Colin indicated its something that uvwasi should accept.

2) Stabilization
  - Land the 2 PRs Michael has submitted
    - https://github.com/nodejs/node/pull/46469
    - https://github.com/nodejs/node/pull/46434
  - Wait a bit until we see we have momentum on maintenance
  - ~~Target to have be stable in Node.js 20 which goes out in April~~
  - Will remove need for command line option. 

3) Implementing the 4 stubbed out socket methods
  - Oscar to talk to Colin to get some help on how to manage streams in order to be able to get started. Will let Michael know once he's got that as he might have some cycles to help with implementation

4) Snapshot 2
  - Longer terms as spec is not defined yet.
  - Guy is going to work on sharing his experimentation/prototyping that he has been doing on this front. Even though this is in JavaScript, agreement is that final implementation for Node.js should be in uvwasi.

5) Finding additional people to contribute (Done)
  - Oscar to reach out to people he knows at bytecode alliance to see if he can get some others interested.
  - We should think about how we make joining our discussion discoverable, something that new people can join and make a call in other ways as well.

**Comment by mhdawson** [comment]
If anybody is interested in contributing or joingin the meeting just let one of us know.

**Comment by abrown** [comment]
I would be interested; it's been on my list of things to do for a while but because I don't have a clear idea of what to do it always ends up low priority.

**Comment by tniessen** [comment]
If there are upcoming meetings regarding WASI, I'd like to join.

**Comment by mhdawson** [comment]
@abrown, @tniessen great to hear that you'd like to join the meetings/help out. 

I'm just setting up the infra to have issues generated for each meeting (https://github.com/nodejs/create-node-meeting-artifacts/pull/124)  and have added the meeting to the Node.js calendar.  The regular meeting is scheduled for every other Wednesday at 2 ET. The next one is scheduled for Wed March 15. 

The zoom for the next meeting will be - https://zoom.us/j/91612484369

**Comment by mhdawson** [comment]
Closed in favor of these issues where ongoing work will be tracked:

https://github.com/nodejs/uvwasi/issues/59
https://github.com/nodejs/uvwasi/issues/200
https://github.com/nodejs/uvwasi/issues/199
