### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by mhdawson** [nodejs/uvwasi#228]
We discussed in last team meeting and we should cut a new release.

**Comment by mcollina** [comment]
Why does the TSC need to approve it?

**Comment by mhdawson** [comment]
oops added the wrong label. Fixing.

**Comment by mhdawson** [comment]
For reference - https://github.com/nodejs/uvwasi/issues/228. Close that issue once the release goes out.

**Comment by mhdawson** [comment]
Release published - https://github.com/nodejs/uvwasi/releases/tag/v0.0.19
