### ISSUE TITLE
Behavior diverge from othe runtimes on empty `fd_read`

### ISSUE THREAD

**Issue by yagehu** [nodejs/uvwasi#260]
`fd_read` or `fd_write` with a 0 length iovec succeeds on host Linux as well as other Wasm runtimes (Wasmer, Wasmtime, WasmEdge, WAMR).  However, uvwasi returns `inval`.  This is a result of libuv performing [null checks](https://github.com/libuv/libuv/blob/8083ab26e0f7c163d131a0509f876f50ed4c110d/src/unix/fs.c#L1996-L1997) at the start of `uv_fs_{read,write}`.

I want to raise this issue to see if maintainers wish to converge with other runtimes here.  0 length read or write should intuitively be a no-op, and we can address this edge case in uvwasi without changing libuv.

**Comment by mhdawson** [comment]
Seems reasonable to me, approved the PR but will give other maintainers a bit of time to review as well.
